import "./globals.css";
import "./layout.style.css"


import type { Metadata } from "next";
import { poppins } from "./fonts";
import { Button } from "@/components/button/button.component";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className='flex items-center'>
          <nav className='flex items-center hola'>
            <div className='flex items-center'>
              <div>
                <p><b>homez</b></p>
              </div>
              <div className='flex items-center'>
                <p>Home</p>
                <p>Listings</p>
                <p>Members</p>
                <p>Blog</p>
                <p>Pages</p>
              </div>
            </div>
            <div className='flex items-center'>
              <div>
                <p>ícono + login/register</p>
              </div>
              <div className='flex items-center'>
                <>
                <Button size="medium" variant="rounded"  color='black'><p>Add Property</p></Button>
                </>
              </div>
              <div>
                <p>símbolo</p>
              </div>
            </div>
          </nav>
        </header>
        
        {children}
      </body>
    </html>
  );
}
