import "./globals.css";
import "./layout.style.css"


import type { Metadata } from "next";
import { poppins } from "./fonts";
import { Button } from "@/components/ui/button/button.component";
import { RxHamburgerMenu } from "react-icons/rx";
import { FaRegCircleUser } from "react-icons/fa6";
import Image from "next/image";
import mainLogo from "../../public/logos/mainLogo.svg"
import Link from "next/link";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
){

  const options = ['Home', 'Listings', 'Members', 'Blog', 'Pages']
  

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className='flex items-center'>
          <div className='flex items-center home'>
            <div className='flex items-center'>
                    <div className='flex items-center logo'>
                        <>
                        <Link href={'/'}>
                        <Image
                          src={mainLogo}
                          alt="screenchot of logo"
                          width={138}
                          height={44}
                          className="hidden md:block"
                        />
                        </Link>
                        </>

                    </div>
              <div className='flex items-center'>
                {options.map((option)=> {
                  return (
                    <div className="div-padding">  
                    <button className="button-hover disables:opacity-50">{option}</button>
                    </div>
                  )
                })}
              </div>
            </div>
            <div className='flex items-center'>
              <div className="separation">
                <div className="flex items-center ">
                  <button className="button-underline">
                    <div className="icon1">
                      <>
                        <FaRegCircleUser />
                      </>
                    </div>
                    <div className="icon2">
                      Login / Register
                    </div>
                  </button>
                </div>
              </div>
              <div className='flex items-center'>
                <>
                <Button size="medium" variant="rounded"  color='black'><p>Add Property</p></Button>
                </>
              </div>
              <div className="icon3">
                <button className="button-hover">
                  <>
                    <RxHamburgerMenu />
                  </>
                </button>
              </div>
            </div>
          </div>
        </header>
        
        {children}
      </body>
    </html>
  );
}
